spring:
  profiles:
    include: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  freemarker:
    template-loader-path: classpath:/mail-templates/
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    task.agile: debug
    org.springframework.security: debug

app:
  mail-from: noreply@taskagile.com
