spring:
  profiles:
    include: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
     org.hibernate.SQL: debug
     org.hibernate.type: trace
     com.taskagile: debug
     org.springframework.security: debug
